// <auto-generated />
namespace _030219.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StudentAttr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentAttr));
        
        string IMigrationMetadata.Id
        {
            get { return "201902030719074_StudentAttr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
